[libraries]
wordwrap = "com.github.davidmoten:word-wrap:0.1.9"

[plugins]
android-library = { id = "com.android.library", version = "7.2.1" }
kotlinter = { id = "org.jmailen.kotlinter", version = "3.10.0" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version = "1.6.21" }
