name: Release
on: 
  push:
    tags:
      - 'v*'
jobs:
  changelog:
    name: Generate changelog
    runs-on: ubuntu-latest
    outputs:
      release_body: ${{ steps.git-cliff.outputs.content }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v2
        id: git-cliff
        with:
          config: .github/workflows/cliff.toml
          args: -vv --latest 
        env:
          OUTPUT: CHANGELOG.md

  build:
    name: Build and publish library
    needs: changelog
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: adopt

      - name: Compile library
        uses: gradle/gradle-command-action@v2
        with:
          arguments: assembleRelease

      - run: mv lib/build/outputs/aar/lib-release.aar noveltomanga-${{ github.ref_name }}.aar

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: NovelToManga ${{ github.ref_name }}
          body: ${{ needs.changelog.outputs.release_body }}
          files: noveltomanga-${{ github.ref_name }}.aar
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
