name: Release
on: 
  workflow_dispatch:
    inputs:
      tag:
        description: 'Version/tag'     
        required: true
jobs:
  build:
    name: Build library
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: adopt

      - name: Compile library
        uses: gradle/gradle-command-action@v2
        with:
          arguments: assembleRelease

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.tag }}
          name: NovelToManga ${{ github.event.inputs.tag }}
          files: lib/build/outputs/aar/lib-release.aar
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
